# -*- coding: utf-8 -*-
"""Untitled31.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/10F4ndrYXfI4Se_dd6O9QdgrWTS7T4EXR
"""

import pandas as pd

E3 = pd.read_excel("classificacoes_publicadas_administracao_publica_e_de_empresas_ciencias_contabeis_e_turismo_2022_1672761148661.xlsx")
ADM = pd.read_excel("classificacoes_publicadas_engenharias_iii_2022_1672761167379.xlsx")

E3_issn = E3["ISSN"].tolist()
ADM2 = ADM[ADM["ISSN"].isin(E3_issn )]

ADM_issn = ADM["ISSN"].tolist()
E3_2 = E3[E3["ISSN"].isin(ADM_issn)]

ADM_E3 = pd.concat([E3_2, ADM2])
ADM_E3 = ADM_E3.drop_duplicates()

ADM_E3.shape

ADM.shape

E3.shape

ADM_E3.to_excel("ADM_E3.xlsx")